# Challenge 2 - ANOVA

In statistics, **Analysis of Variance (ANOVA)** is also used to analyze the differences among group means. The difference between t-test and ANOVA is the former is ued to compare two groups whereas the latter is used to compare three or more groups. [Read more about the difference between t-test and ANOVA](https://keydifferences.com/difference-between-t-test-and-anova.html).

From the ANOVA test, you receive two numbers. The first number is called the **F-value** which indicates whether your null-hypothesis can be rejected. The critical F-value that rejects the null-hypothesis varies according to the number of total subjects and the number of subject groups in your experiment. In [this table](https://www.itl.nist.gov/div898/handbook/eda/section3/eda3673.htm) you can find the critical values of the F distribution. **If you are confused by the massive F-distribution table, don't worry. Skip F-value for now and study it at a later time. In this challenge you only need to look at the p-value.**

The p-value is another number yielded by ANOVA which already takes the number of total subjects and the number of experiment groups into consideration. **Typically if your p-value is less than 0.05, you can declare the null-hypothesis is rejected.**

In this challenge, we want to understand whether there are significant differences among various types of pokemons' `Total` value, i.e. Grass vs Poison vs Fire vs Dragon... There are many types of pokemons which makes it a perfect use case for ANOVA.

In [1]:
# Import libraries

import pandas as pd

In [2]:
# Import dataset

pokemon = pd.read_csv('../../lab-df-calculation-and-transformation/your-code/Pokemon.csv')

pokemon.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

**To achieve our goal, we use three steps:**

1. **Extract the unique values of the pokemon types.**

1. **Select dataframes for each unique pokemon type.**

1. **Conduct ANOVA analysis across the pokemon types.**

#### First let's obtain the unique values of the pokemon types. These values should be extracted from Type 1 and Type 2 aggregated. Assign the unique values to a variable called `unique_types`.

*Hint: the correct number of unique types is 19 including `NaN`. You can disregard `NaN` in next step.*

In [74]:
# Your code here
# unique_types = 
list(pokemon["Type 1"].unique())
list(pokemon['Type 2'].unique())
x = list(pokemon["Type 1"].unique()) + list(pokemon["Type 2"].unique())
unique_types = set(x)
len(unique_types) # you should see 19

19

In [133]:
unique_types2 = list(pokemon["Type 1"].unique())
unique_types2

['Grass',
 'Fire',
 'Water',
 'Bug',
 'Normal',
 'Poison',
 'Electric',
 'Ground',
 'Fairy',
 'Fighting',
 'Psychic',
 'Rock',
 'Ghost',
 'Ice',
 'Dragon',
 'Dark',
 'Steel',
 'Flying']

#### Second we will create a list named `pokemon_totals` to contain the `Total` values of each unique type of pokemons.

Why we use a list instead of a dictionary to store the pokemon `Total`? It's because ANOVA only tells us whether there is a significant difference of the group means but does not tell which group(s) are significantly different. Therefore, we don't need know which `Total` belongs to which pokemon type.

*Hints:*

* Loop through `unique_types` and append the selected type's `Total` to `pokemon_groups`.
* Skip the `NaN` value in `unique_types`. `NaN` is a `float` variable which you can find out by using `type()`. The valid pokemon type values are all of the `str` type.
* At the end, the length of your `pokemon_totals` should be 18.

In [184]:
poke = pd.DataFrame(pokemon[['Name','Type 1','Total']])
poke.set_index('Type 1',inplace=True)
pokemon.set_index('Name',inplace=True)
poke.head()
pokemon

,#,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,,,
Bulbasaur,1,Grass,Poison,318,45,49,49,65,65,45,1,False
Ivysaur,2,Grass,Poison,405,60,62,63,80,80,60,1,False
Venusaur,3,Grass,Poison,525,80,82,83,100,100,80,1,False
VenusaurMega Venusaur,3,Grass,Poison,625,80,100,123,122,120,80,1,False
Charmander,4,Fire,NaN,309,39,52,43,60,50,65,1,False
Charmeleon,5,Fire,NaN,405,58,64,58,80,65,80,1,False
Charizard,6,Fire,Flying,534,78,84,78,109,85,100,1,False
CharizardMega Charizard X,6,Fire,Dragon,634,78,130,111,130,85,100,1,False
CharizardMega Charizard Y,6,Fire,Flying,634,78,104,78,159,115,100,1,False
Squirtle,7,Water,NaN,314,44,48,65,50,64,43,1,False
Wartortle,8,Water,NaN,405,59,63,80,65,80,58,1,False
Blastoise,9,Water,NaN,530,79,83,100,85,105,78,1,False
BlastoiseMega Blastoise,9,Water,NaN,630,79,103,120,135,115,78,1,False
Caterpie,10,Bug,NaN,195,45,30,35,20,20,45,1,False
Metapod,11,Bug,NaN,205,50,20,55,25,25,30,1,False
Butterfree,12,Bug,Flying,395,60,45,50,90,80,70,1,False
Weedle,13,Bug,Poison,195,40,35,30,20,20,50,1,False
Kakuna,14,Bug,Poison,205,45,25,50,25,25,35,1,False
Beedrill,15,Bug,Poison,395,65,90,40,45,80,75,1,False
BeedrillMega Beedrill,15,Bug,Poison,495,65,150,40,15,80,145,1,False
Pidgey,16,Normal,Flying,251,40,45,40,35,35,56,1,False
Pidgeotto,17,Normal,Flying,349,63,60,55,50,50,71,1,False
Pidgeot,18,Normal,Flying,479,83,80,75,70,70,101,1,False
PidgeotMega Pidgeot,18,Normal,Flying,579,83,80,80,135,80,121,1,False
Rattata,19,Normal,NaN,253,30,56,35,25,35,72,1,False
Raticate,20,Normal,NaN,413,55,81,60,50,70,97,1,False
Spearow,21,Normal,Flying,262,40,60,30,31,31,70,1,False
Fearow,22,Normal,Flying,442,65,90,65,61,61,100,1,False
Ekans,23,Poison,NaN,288,35,60,44,40,54,55,1,False
Arbok,24,Poison,NaN,438,60,85,69,65,79,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
Sylveon,700,Fairy,NaN,525,95,65,65,110,130,60,6,False
Hawlucha,701,Fighting,Flying,500,78,92,75,74,63,118,6,False
Dedenne,702,Electric,Fairy,431,67,58,57,81,67,101,6,False
Carbink,703,Rock,Fairy,500,50,50,150,50,150,50,6,False
Goomy,704,Dragon,NaN,300,45,50,35,55,75,40,6,False
Sliggoo,705,Dragon,NaN,452,68,75,53,83,113,60,6,False
Goodra,706,Dragon,NaN,600,90,100,70,110,150,80,6,False
Klefki,707,Steel,Fairy,470,57,80,91,80,87,75,6,False
Phantump,708,Ghost,Grass,309,43,70,48,50,60,38,6,False
Trevenant,709,Ghost,Grass,474,85,110,76,65,82,56,6,False
PumpkabooAverage Size,710,Ghost,Grass,335,49,66,70,44,55,51,6,False
PumpkabooSmall Size,710,Ghost,Grass,335,44,66,70,44,55,56,6,False
PumpkabooLarge Size,710,Ghost,Grass,335,54,66,70,44,55,46,6,False
PumpkabooSuper Size,710,Ghost,Grass,335,59,66,70,44,55,41,6,False
GourgeistAverage Size,711,Ghost,Grass,494,65,90,122,58,75,84,6,False
GourgeistSmall Size,711,Ghost,Grass,494,55,85,122,58,75,99,6,False
GourgeistLarge Size,711,Ghost,Grass,494,75,95,122,58,75,69,6,False
GourgeistSuper Size,711,Ghost,Grass,494,85,100,122,58,75,54,6,False
Bergmite,712,Ice,NaN,304,55,69,85,32,35,28,6,False
Avalugg,713,Ice,NaN,514,95,117,184,44,46,28,6,False
Noibat,714,Flying,Dragon,245,40,30,35,45,40,55,6,False
Noivern,715,Flying,Dragon,535,85,70,80,97,80,123,6,False
Xerneas,716,Fairy,NaN,680,126,131,95,131,98,99,6,True
Yveltal,717,Dark,Flying,680,126,131,95,131,98,99,6,True
Zygarde50% Forme,718,Dragon,Ground,600,108,100,121,81,95,95,6,True
Diancie,719,Rock,Fairy,600,50,100,150,100,150,50,6,True
DiancieMega Diancie,719,Rock,Fairy,700,50,160,110,160,110,110,6,True
HoopaHoopa Confined,720,Psychic,Ghost,600,80,110,60,150,130,70,6,True
HoopaHoopa Unbound,720,Psychic,Dark,680,80,160,60,170,130,80,6,True
Volcanion,721,Fire,Water,600,80,110,120,130,90,70,6,True

In [186]:
# Your code here
pokemon_totals = []
pc =[]
for i in unique_types2:
#     b = poke.loc[i]
    r = pokemon[pokemon['Type 1']==i]['Total']
    pokemon_totals.append(r)
#     pc.append(b)
print(pokemon_totals)
# print(pc)
len(pokemon_totals) # you should see 18

[Name
Bulbasaur                318
Ivysaur                  405
Venusaur                 525
VenusaurMega Venusaur    625
Oddish                   320
                        ...
Chespin                  313
Quilladin                405
Chesnaught               530
Skiddo                   350
Gogoat                   531
Name: Total, Length: 70, dtype: int64, Name
Charmander                   309
Charmeleon                   405
Charizard                    534
CharizardMega Charizard X    634
CharizardMega Charizard Y    634
Vulpix                       299
Ninetales                    505
Growlithe                    350
Arcanine                     555
Ponyta                       410
Rapidash                     500
Magmar                       495
Flareon                      525
Moltres                      580
Cyndaquil                    309
Quilava                      405
Typhlosion                   534
Slugma                       250
Magcargo                     410
Magby                        365
Entei                        580
Ho-oh                        680
Torchic                      310
Combusken                    405
Blaziken                     530
BlazikenMega Blaziken        630
Numel                        305
Camerupt                     460
CameruptMega Camerupt        560
Torkoal                      470
Chimchar                     309
Monferno                     405
Infernape                    534
Magmortar                    540
Heatran                      600
Tepig                        308
Pignite                      418
Emboar                       528
Pansear                      316
Simisear                     498
Darumaka                     315
DarmanitanStandard Mode      480
DarmanitanZen Mode           540
Heatmor                      484
Fennekin                     307
Braixen                      409
Delphox                      534
Fletchinder                  382
Talonflame                   499
Litleo                       369
Pyroar                       507
Volcanion                    600
Name: Total, dtype: int64, Name
Squirtle                   314
Wartortle                  405
Blastoise                  530
BlastoiseMega Blastoise    630
Psyduck                    320
                          ...
Froakie                    314
Frogadier                  405
Greninja                   530
Clauncher                  330
Clawitzer                  500
Name: Total, Length: 112, dtype: int64, Name
Caterpie      195
Metapod       205
Butterfree    395
Weedle        195
Kakuna        205
             ...
Volcarona     550
Genesect      600
Scatterbug    200
Spewpa        213
Vivillon      411
Name: Total, Length: 69, dtype: int64, Name
Pidgey                     251
Pidgeotto                  349
Pidgeot                    479
PidgeotMega Pidgeot        579
Rattata                    253
                          ...
MeloettaPirouette Forme    600
Bunnelby                   237
Diggersby                  423
Fletchling                 278
Furfrou                    472
Name: Total, Length: 98, dtype: int64, Name
Ekans        288
Arbok        438
Nidoran♀     275
Nidorina     365
Nidoqueen    505
Nidoran♂     273
Nidorino     365
Nidoking     505
Zubat        245
Golbat       455
Grimer       325
Muk          500
Koffing      340
Weezing      490
Crobat       535
Gulpin       302
Swalot       467
Seviper      458
Stunky       329
Skuntank     479
Skorupi      330
Drapion      500
Croagunk     300
Toxicroak    490
Trubbish     329
Garbodor     474
Skrelp       320
Dragalge     494
Name: Total, dtype: int64, Name
Pikachu                     320
Raichu                      485
Magnemite                   325
Magneton                    465
Voltorb                     330
Electrode                   480
Electabuzz                  490
Jolteon                     525
Zapdos                      580
Pichu                       205
Mareep                      280
Flaaffy                     365
Ampharos                    510
AmpharosMega Ampharos       610
Elekid                      360
Raikou                      580
Electrike                   295
Manectric                   475
ManectricMega Manectric     575
Plusle                      405
Minun                       405
Shinx                       263
Luxio                       363
Luxray                      523
Pachirisu                   405
Magnezone                   535
Electivire                  540
Rotom                       440
RotomHeat Rotom             520
RotomWash Rotom             520
RotomFrost Rotom            520
RotomFan Rotom              520
RotomMow Rotom              520
Blitzle                     295
Zebstrika                   497
Emolga                      428
Tynamo                      275
Eelektrik                   405
Eelektross                  515
ThundurusIncarnate Forme    580
ThundurusTherian Forme      580
Helioptile                  289
Heliolisk                   481
Dedenne                     431
Name: Total, dtype: int64, Name
Sandshrew                  300
Sandslash                  450
Diglett                    265
Dugtrio                    405
Cubone                     320
Marowak                    425
Rhyhorn                    345
Rhydon                     485
Gligar                     430
Phanpy                     330
Donphan                    500
Trapinch                   290
Vibrava                    340
Flygon                     520
Baltoy                     300
Claydol                    500
Groudon                    670
GroudonPrimal Groudon      770
Hippopotas                 330
Hippowdon                  525
Rhyperior                  535
Gliscor                    510
Drilbur                    328
Excadrill                  508
Sandile                    292
Krokorok                   351
Krookodile                 519
Stunfisk                   471
Golett                     303
Golurk                     483
LandorusIncarnate Forme    600
LandorusTherian Forme      600
Name: Total, dtype: int64, Name
Clefairy      323
Clefable      483
Cleffa        218
Togepi        245
Togetic       405
Snubbull      300
Granbull      450
Togekiss      545
Flabébé       303
Floette       371
Florges       552
Spritzee      341
Aromatisse    462
Swirlix       341
Slurpuff      480
Sylveon       525
Xerneas       680
Name: Total, dtype: int64, Name
Mankey                   305
Primeape                 455
Machop                   305
Machoke                  405
Machamp                  505
Hitmonlee                455
Hitmonchan               455
Tyrogue                  210
Hitmontop                455
Makuhita                 237
Hariyama                 474
Meditite                 280
Medicham                 410
MedichamMega Medicham    510
Riolu                    285
Lucario                  525
LucarioMega Lucario      625
Timburr                  305
Gurdurr                  405
Conkeldurr               505
Throh                    465
Sawk                     465
Mienfoo                  350
Mienshao                 510
Pancham                  348
Pangoro                  495
Hawlucha                 500
Name: Total, dtype: int64, Name
Abra                       310
Kadabra                    400
Alakazam                   500
AlakazamMega Alakazam      590
Drowzee                    328
Hypno                      483
Mr. Mime                   460
Mewtwo                     680
MewtwoMega Mewtwo X        780
MewtwoMega Mewtwo Y        780
Mew                        600
Natu                       320
Xatu                       470
Espeon                     525
Unown                      336
Wobbuffet                  405
Lugia                      680
Celebi                     600
Ralts                      198
Kirlia                     278
Gardevoir                  518
GardevoirMega Gardevoir    618
Spoink                     330
Grumpig                    470
Chimecho                   425
Wynaut                     260
DeoxysNormal Forme         600
DeoxysAttack Forme         600
DeoxysDefense Forme        600
DeoxysSpeed Forme          600
Chingling                  285
Mime Jr.                   310
Gallade                    518
GalladeMega Gallade        618
Uxie                       580
Mesprit                    580
Azelf                      580
Cresselia                  600
Victini                    600
Munna                      292
Musharna                   487
Woobat                     313
Swoobat                    425
Sigilyph                   490
Gothita                    290
Gothorita                  390
Gothitelle                 490
Solosis                    290
Duosion                    370
Reuniclus                  490
Elgyem                     335
Beheeyem                   485
Espurr                     355
MeowsticMale               466
MeowsticFemale             466
HoopaHoopa Confined        600
HoopaHoopa Unbound         680
Name: Total, dtype: int64, Name
Geodude                      300
Graveler                     390
Golem                        495
Onix                         385
Omanyte                      355
Omastar                      495
Kabuto                       355
Kabutops                     495
Aerodactyl                   515
AerodactylMega Aerodactyl    615
Sudowoodo                    410
Larvitar                     300
Pupitar                      410
Tyranitar                    600
TyranitarMega Tyranitar      700
Nosepass                     375
Lunatone                     440
Solrock                      440
Lileep                       355
Cradily                      495
Anorith                      355
Armaldo                      495
Regirock                     580
Cranidos                     350
Rampardos                    495
Shieldon                     350
Bastiodon                    495
Bonsly                       290
Probopass                    525
Roggenrola                   280
Boldore                      390
Gigalith                     515
Archen                       401
Archeops                     567
Terrakion                    580
Binacle                      306
Barbaracle                   500
Tyrunt                       362
Tyrantrum                    521
Amaura                       362
Aurorus                      521
Carbink                      500
Diancie                      600
DiancieMega Diancie          700
Name: Total, dtype: int64, Name
Gastly                   310
Haunter                  405
Gengar                   500
GengarMega Gengar        600
Misdreavus               435
Shuppet                  295
Banette                  455
BanetteMega Banette      555
Duskull                  295
Dusclops                 455
Drifloon                 348
Drifblim                 498
Mismagius                495
Spiritomb                485
Dusknoir                 525
GiratinaAltered Forme    680
GiratinaOrigin Forme     680
Yamask                   303
Cofagrigus               483
Litwick                  275
Lampent                  370
Chandelure               520
Phantump                 309
Trevenant                474
PumpkabooAverage Size    335
PumpkabooSmall Size      335
PumpkabooLarge Size      335
PumpkabooSuper Size      335
GourgeistAverage Size    494
GourgeistSmall Size      494
GourgeistLarge Size      494
GourgeistSuper Size      494
Name: Total, dtype: int64, Name
Jynx                 455
Articuno             580
Swinub               250
Piloswine            450
Delibird             330
Smoochum             305
Snorunt              300
Glalie               480
GlalieMega Glalie    580
Spheal               290
Sealeo               410
Walrein              530
Regice               580
Glaceon              525
Mamoswine            530
Froslass             480
Vanillite            305
Vanillish            395
Vanilluxe            535
Cubchoo              305
Beartic              485
Cryogonal            485
Bergmite             304
Avalugg              514
Name: Total, dtype: int64, Name
Dratini                    300
Dragonair                  420
Dragonite                  600
Altaria                    490
AltariaMega Altaria        590
Bagon                      300
Shelgon                    420
Salamence                  600
SalamenceMega Salamence    700
Latias                     600
LatiasMega Latias          700
Latios                     600
LatiosMega Latios          700
Rayquaza                   680
RayquazaMega Rayquaza      780
Gible                      300
Gabite                     410
Garchomp                   600
GarchompMega Garchomp      700
Axew                       320
Fraxure                    410
Haxorus                    540
Druddigon                  485
Reshiram                   680
Zekrom                     680
Kyurem                     660
KyuremBlack Kyurem         700
KyuremWhite Kyurem         700
Goomy                      300
Sliggoo                    452
Goodra                     600
Zygarde50% Forme           600
Name: Total, dtype: int64, Name
Umbreon                  525
Murkrow                  405
Sneasel                  430
Houndour                 330
Houndoom                 500
HoundoomMega Houndoom    600
Poochyena                220
Mightyena                420
Sableye                  380
SableyeMega Sableye      480
Absol                    465
AbsolMega Absol          565
Honchkrow                505
Weavile                  510
Darkrai                  600
Purrloin                 281
Liepard                  446
Scraggy                  348
Scrafty                  488
Zorua                    330
Zoroark                  510
Pawniard                 340
Bisharp                  490
Vullaby                  370
Mandibuzz                510
Deino                    300
Zweilous                 420
Hydreigon                600
Inkay                    288
Malamar                  482
Yveltal                  680
Name: Total, dtype: int64, Name
Steelix                    510
SteelixMega Steelix        610
Skarmory                   465
Mawile                     380
MawileMega Mawile          480
Aron                       330
Lairon                     430
Aggron                     530
AggronMega Aggron          630
Beldum                     300
Metang                     420
Metagross                  600
MetagrossMega Metagross    700
Registeel                  580
Jirachi                    600
Bronzor                    300
Bronzong                   500
Dialga                     680
Klink                      300
Klang                      440
Klinklang                  520
Cobalion                   580
Honedge                    325
Doublade                   448
AegislashBlade Forme       520
AegislashShield Forme      520
Klefki                     470
Name: Total, dtype: int64, Name
TornadusIncarnate Forme    580
TornadusTherian Forme      580
Noibat                     245
Noivern                    535
Name: Total, dtype: int64]

18

#### Now we run ANOVA test on `pokemon_totals`.

*Hints:*

* To conduct ANOVA, you can use `scipy.stats.f_oneway()`. Here's the [reference](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.f_oneway.html).

* What if `f_oneway` throws an error because it does not accept `pokemon_totals` as a list? The trick is to add a `*` in front of `pokemon_totals`, e.g. `stats.f_oneway(*pokemon_groups)`. This trick breaks the list and supplies each list item as a parameter for `f_oneway`.

In [188]:
# Your code here
import scipy.stats
scipy.stats.f_oneway(*pokemon_totals)

F_onewayResult(statistic=4.63876748166055, pvalue=2.077215448842098e-09)

#### Interpret the ANOVA test result. Is the difference significant?

In [ ]:
# Your comment here
#No it is not