# Challenge 3

In this challenge we will work on the `Orders.csv` data set in the previous [Subsetting and Descriptive Stats lab](../../lab-subsetting-and-descriptive-stats/your-code/main.ipynb). In your work you will apply the thinking process and workflow we showed you in Challenge 2.

You are serving as a Business Intelligence Analyst at the headquarter of an international fashion goods chain store. Your boss today asked you to do two things for her:

**First, identify two groups of customers from the data set.** The first group is **VIP Customers** whose **aggregated expenses** at your global chain stores are **above the 95th percentile** (aka. 0.95 quantile). The second group is **Preferred Customers** whose **aggregated expenses** are **between the 75th and 95th percentile**.

**Second, identify which country has the most of your VIP customers, and which country has the most of your VIP+Preferred Customers combined.**

# Q1: How to identify VIP & Preferred Customers?

We start by importing all the required libraries:

In [84]:
# import required libraries
import pandas as pd
import numpy as np
import re
from scipy import stats

Next, import `Orders.csv` from the "subsetting" lab folder into a dataframe variable called `orders`. Print the head of `orders` to overview the data:

In [85]:
# enter your code here
orders = pd.read_csv("../../lab-subsetting-and-descriptive-stats/your-code/Orders.csv")
orders.head()

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent
0,0,536365,85123A,2010,12,3,8,white hanging heart t-light holder,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,1,536365,71053,2010,12,3,8,white metal lantern,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,2,536365,84406B,2010,12,3,8,cream cupid hearts coat hanger,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,3,536365,84029G,2010,12,3,8,knitted union flag hot water bottle,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,4,536365,84029E,2010,12,3,8,red woolly hottie white heart.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34

---

"Identify VIP and Preferred Customers" is the non-technical goal of your boss. You need to translate that goal into technical languages that data analysts use:

## How to label customers whose aggregated `amount_spent` is in a given quantile range?

We break down the main problem into several sub problems:

#### Sub Problem 1: How to aggregate the  `amount_spent` for unique customers?

#### Sub Problem 2: How to select customers whose aggregated `amount_spent` is in a given quantile range?

#### Sub Problem 3: How to label selected customers as "VIP" or "Preferred"?

*Note: If you want to break down the main problem in a different way, please feel free to revise the sub problems above.*

Now in the workspace below, tackle each of the sub problems using the iterative problem solving workflow. Insert cells as necessary to write your codes and explain your steps.

In [103]:
# your code here


cust_group=orders[['CustomerID','amount_spent']]

orders['Amount_Spent'] = orders['amount_spent'].groupby(orders['CustomerID']).transform('sum')
orders.head()

orders2= orders.drop_duplicates(subset='CustomerID')

# orders.shape 
vip_cust= orders2['Amount_Spent'].quantile(.95)
pref_cust= orders2['Amount_Spent'].quantile(.75)

orders2['Status']= orders2['Amount_Spent']>= vip_cust

orders2

/Users/talalagedeon/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent,Amount_Spent,Status
0,0,536365,85123A,2010,12,3,8,white hanging heart t-light holder,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,5391.21,False
9,9,536367,84879,2010,12,3,8,assorted colour bird ornament,32,2010-12-01 08:34:00,1.69,13047,United Kingdom,54.08,3237.54,False
26,26,536370,22728,2010,12,3,8,alarm clock bakelike pink,24,2010-12-01 08:45:00,3.75,12583,France,90.00,7281.38,True
46,46,536371,22086,2010,12,3,9,paper chain kit 50's christmas,80,2010-12-01 09:00:00,2.55,13748,United Kingdom,204.00,948.25,False
65,65,536374,21258,2010,12,3,9,victorian sewing box large,32,2010-12-01 09:09:00,10.95,15100,United Kingdom,350.40,876.00,False
82,82,536376,22114,2010,12,3,9,hot water bottle tea and sympathy,48,2010-12-01 09:32:00,3.45,15291,United Kingdom,165.60,4668.30,False
86,86,536378,22386,2010,12,3,9,jumbo bag pink polkadot,10,2010-12-01 09:37:00,1.95,14688,United Kingdom,19.50,5630.87,False
105,105,536380,22961,2010,12,3,9,jam making set printed,24,2010-12-01 09:41:00,1.45,17809,United Kingdom,34.80,5411.91,False
106,106,536381,22139,2010,12,3,9,retrospot tea set ceramic 11 pc,23,2010-12-01 09:41:00,4.25,15311,United Kingdom,97.75,60767.90,True
141,142,536382,10002,2010,12,3,9,inflatable political globe,12,2010-12-01 09:45:00,0.85,16098,United Kingdom,10.20,2005.63,False
153,155,536384,82484,2010,12,3,9,wood black board ant white finish,3,2010-12-01 09:53:00,6.45,18074,United Kingdom,19.35,489.60,False
166,168,536385,22783,2010,12,3,9,set 3 wicker oval baskets w lids,1,2010-12-01 09:56:00,19.95,17420,United Kingdom,19.95,598.83,False
173,175,536386,84880,2010,12,3,9,white wire egg holder,36,2010-12-01 09:57:00,4.95,16029,United Kingdom,178.20,81024.84,True
181,183,536388,21754,2010,12,3,9,home building block word,3,2010-12-01 09:59:00,5.95,16250,United Kingdom,17.85,389.44,False
195,197,536389,22941,2010,12,3,10,christmas lights 10 reindeer,6,2010-12-01 10:03:00,8.50,12431,Australia,51.00,6487.45,True
209,211,536390,22941,2010,12,3,10,christmas lights 10 reindeer,2,2010-12-01 10:19:00,8.50,17511,United Kingdom,17.00,91062.38,True
233,242,536392,22150,2010,12,3,10,3 stripey mice feltcraft,6,2010-12-01 10:29:00,1.95,13705,United Kingdom,11.70,711.86,False
243,252,536393,22180,2010,12,3,10,retrospot lamp,8,2010-12-01 10:37:00,9.95,13747,United Kingdom,79.60,79.60,False
244,253,536394,21506,2010,12,3,10,"fancy font birthday card,",24,2010-12-01 10:39:00,0.42,13408,United Kingdom,10.08,28117.04,True
255,264,536395,22188,2010,12,3,10,black heart card holder,8,2010-12-01 10:47:00,3.95,13767,United Kingdom,31.60,17220.36,True
287,296,536397,35004B,2010,12,3,10,set of 3 black flying ducks,12,2010-12-01 10:51:00,4.65,17924,United Kingdom,55.80,2962.50,False
289,298,536398,21980,2010,12,3,10,pack of 12 red retrospot tissues,24,2010-12-01 10:52:00,0.29,13448,United Kingdom,6.96,3539.37,False
309,318,536401,22110,2010,12,3,11,bird house hot water bottle,1,2010-12-01 11:21:00,2.55,15862,United Kingdom,2.55,832.88,False
373,382,536402,22086,2010,12,3,11,paper chain kit 50's christmas,40,2010-12-01 11:22:00,2.55,15513,United Kingdom,102.00,14758.22,True
376,385,536403,22867,2010,12,3,11,hand warmer bird design,96,2010-12-01 11:27:00,1.85,12791,Netherlands,177.60,192.60,False
378,387,536404,22297,2010,12,3,11,heart ivory trellis small,24,2010-12-01 11:29:00,1.25,16218,United Kingdom,30.00,3084.68,False
406,415,536405,20914,2010,12,3,11,set/5 red retrospot lid glass bowls,128,2010-12-01 11:32:00,2.55,14045,United Kingdom,326.40,1659.75,False
426,435,536408,22537,2010,12,3,11,magic drawing slate dinosaur,24,2010-12-01 11:41:00,0.42,14307,United Kingdom,10.08,2995.72,False
474,483,536409,90199C,2010,12,3,11,5 strand glass necklace crystal,3,2010-12-01 11:45:00,6.35,17908,United Kingdom,19.05,243.28,False
532,541,536412,20728,2010,12,3,11,lunch bag cars blue,3,2010-12-01 11:49:00,1.65,17920,United Kingdom,4.95,4204.10,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385539,522968,580490,22233,2011,12,7,12,jigsaw rabbit and birdhouse,12,2011-12-04 12:48:00,0.59,15773,United Kingdom,7.08,635.68,False
385785,523214,580504,23014,2011,12,7,13,glass apothecary bottle elixir,1,2011-12-04 13:32:00,3.95,17936,United Kingdom,3.95,389.84,False
386432,523945,580526,22596,2011,12,7,15,christmas star wish list chalkboard,12,2011-12-04 15:18:00,1.25,16535,United Kingdom,15.00,593.75,False
386647,524160,580535,23571,2011,12,7,16,traditional naughts & crosses,12,2011-12-04 16:02:00,1.65,16988,United Kingdom,19.80,126.12,False
388287,526348,580664,84832,2011,12,1,14,zinc willie winkie candle stick,6,2011-12-05 14:03:00,0.85,15097,United Kingdom,5.10,248.08,False
388782,526846,580678,22069,2011,12,1,14,brown pirate treasure chest,14,2011-12-05 14:49:00,0.39,18015,United Kingdom,5.46,120.03,False
388951,527022,580690,22319,2011,12,1,15,hairclips forties fabric assorted,108,2011-12-05 15:44:00,0.19,16597,United Kingdom,20.52,90.04,False
388958,527029,580691,20996,2011,12,1,15,jazz hearts address book,24,2011-12-05 15:48:00,0.19,13790,United Kingdom,4.56,348.80,False
389231,527305,580700,23080,2011,12,1,16,red metal box top secret,2,2011-12-05 16:23:00,8.25,14219,United Kingdom,16.50,89.94,False
389294,527384,580716,85227,2011,12,1,16,set of 6 3d kit cards for kids,12,2011-12-05 16:48:00,0.85,12367,Denmark,10.20,168.90,False
390003,529479,580731,22810,2011,12,1,17,set of 6 t-lights snowmen,1,2011-12-05 17:36:00,2.95,17383,United Kingdom,2.95,199.29,False
390246,529740,580752,POST,2011,12,2,9,postage,3,2011-12-06 09:56:00,45.00,12478,Greece,135.00,680.99,False
390447,530032,580772,22839,2011,12,2,11,3 tier cake tin green and cream,1,2011-12-06 11:00:00,14.95,15992,United Kingdom,14.95,41.99,False
390557,530144,580819,21373,2011,12,2,11,mirrored wall art snowflakes,12,2011-12-06 11:30:00,0.75,15318,United Kingdom,9.00,312.62,False
390776,530374,580865,22645,2011,12,2,11,ceramic heart fairy cake money bank,1,2011-12-06 11:58:00,0.39,17914,United Kingdom,0.39,336.43,False
391421,531020,580901,22464,2011,12,2,12,hanging metal heart lantern,12,2011-12-06 12:45:00,0.79,16528,United Kingdom,9.48,244.41,False
391792,531420,580955,21974,2011,12,2,14,set of 36 paisley flower doilies,12,2011-12-06 14:22:00,1.45,12442,Spain,17.40,172.06,False
392222,531881,580977,21137,2011,12,2,15,black record cover frame,12,2011-12-06 15:32:00,3.75,16569,United Kingdom,45.00,124.20,False
392403,532691,580986,22757,2011,12,2,16,large red babushka notebook,12,2011-12-06 16:34:00,0.39,12650,France,4.68,314.44,False
392444,532735,580996,17003,2011,12,2,17,brocade ring purse,72,2011-12-06 17:18:00,0.39,14578,United Kingdom,28.08,168.63,False
393220,533733,581105,85152,2011,12,3,12,hand over the chocolate sign,620,2011-12-07 12:14:00,1.92,16000,United Kingdom,1190.40,12393.70,True
393298,533812,581115,22413,2011,12,3,12,metal sign take it or leave it,1404,2011-12-07 12:20:00,2.75,15195,United Kingdom,3861.00,3861.00,False
393393,533916,581125,22422,2011,12,3,12,toothpaste tube pen,18,2011-12-07 12:41:00,0.12,14087,United Kingdom,2.16,194.42,False
393723,534247,581142,23156,2011,12,3,13,set of 5 mini grocery magnets,1,2011-12-07 13:38:00,2.08,14204,United Kingdom,2.08,161.03,False
393946,534480,581149,23333,2011,12,3,14,ivory wicker heart medium,3,2011-12-07 14:12:00,1.25,15471,United Kingdom,3.75,469.48,False
394965,536969,581233,22178,2011,12,4,10,victorian glass hanging t-light,6,2011-12-08 10:33:00,1.95,13436,United Kingdom,11.70,196.89,False
395041,537255,581241,22922,2011,12,4,10,fridge magnets us diner assorted,12,2011-12-08 10:58:00,0.85,15520,United Kingdom,10.20,343.50,False
395777,538064,581385,84029G,2011,12,4,13,knitted union flag hot water bottle,24,2011-12-08 13:11:00,3.75,13298,United Kingdom,90.00,360.00,False
396506,538812,581416,22466,2011,12,4,14,fairy tale cottage night light,1,2011-12-08 14:58:00,1.95,14569,United Kingdom,1.95,227.39,False
397783,541768,581578,POST,2011,12,5,12,postage,3,2011-12-09 12:16:00,18.00,12713,Germany,54.00,848.55,False

Now we'll leave it to you to solve Q2 & Q3, which you can leverage from your solution for Q1:

# Q2: How to identify which country has the most VIP Customers?

# Q3: How to identify which country has the most VIP+Preferred Customers combined?

Provide your solution for Q2 below:

In [107]:
orders_vip = orders2[orders2['Status'] == True].drop_duplicates(subset = ['CustomerID', 'Country'])['Country'].value_counts()
orders_vip

United Kingdom     177
Germany             10
France               9
Switzerland          3
Spain                2
EIRE                 2
Japan                2
Australia            2
Portugal             2
Singapore            1
Sweden               1
Denmark              1
Finland              1
Cyprus               1
Channel Islands      1
Netherlands          1
Norway               1
Name: Country, dtype: int64

In [6]:
# your code here